name: Weekly Publish

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:

  setup:
    name: Setup Publish
    runs-on: ubuntu-latest
    outputs:
      commits_today: ${{ steps.commits.outputs.commits_today }}
      date: ${{ steps.date.outputs.date }}
    if: github.repository_owner == 'w3c' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Print Latest Commit
        run: echo ${{ github.sha }}

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  publish:
    name: Publish
    needs: [setup]
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        tag: ["weekly-${{needs.setup.outputs.date}}", weekly]
    with:
      tag: ${{ matrix.tag }}
      platforms: "linux/amd64,linux/arm64"
